-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Servidor: sql305.byetcluster.com
-- Tiempo de generación: 21-04-2024 a las 17:03:16
-- Versión del servidor: 10.4.17-MariaDB
-- Versión de PHP: 7.2.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `if0_36405657_pregunta`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `respuestas`
--

CREATE TABLE `respuestas` (
  `id` int(11) NOT NULL,
  `resultados` varchar(2500) DEFAULT NULL,
  `Palabra_1` varchar(15) NOT NULL,
  `Palabra_2` varchar(15) DEFAULT NULL,
  `Palabra_3` varchar(15) DEFAULT NULL,
  `Palabra_4` varchar(15) DEFAULT NULL,
  `Palabra_5` varchar(15) DEFAULT NULL,
  `Palabra_6` varchar(15) DEFAULT NULL,
  `Palabra_7` varchar(15) DEFAULT NULL,
  `Palabra_8` varchar(15) DEFAULT NULL,
  `Palabra_9` varchar(15) DEFAULT NULL,
  `Palabra_10` varchar(15) DEFAULT NULL,
  `single_response` varchar(5) NOT NULL,
  `required_words` varchar(24) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `respuestas`
--

INSERT INTO `respuestas` (`id`, `resultados`, `Palabra_1`, `Palabra_2`, `Palabra_3`, `Palabra_4`, `Palabra_5`, `Palabra_6`, `Palabra_7`, `Palabra_8`, `Palabra_9`, `Palabra_10`, `single_response`, `required_words`) VALUES
(1, 'recuerda que soy un modelo en aprendizaje :) mientras mas especifico seas mejor te entenderé', 'maritima', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'False', ''),
(2, 'La inscripción extemporánea se refiere al proceso de registrarse para una asignatura, curso o programa de estudios después de la fecha límite establecida por la universidad. En otras palabras, es un registro tardío que se realiza fuera del período de inscripción regular.\r\nsi esta interesado en la inscripción extemporánea puede rellenar la siguiente plantilla:\r\n http://www.umc.edu.ve/pdf/escuelas/ingenieria/Inscripcionextemporanea.pdf\r\n\r\nsiga los pasos que describe la misma', 'solicitud', 'extemporanea', 'estemporanea', 'extemporaneo', 'solicitudes', 'planilla', 'plantilla', NULL, NULL, NULL, 'True', 'extemporanea'),
(3, 'Si eres nuevo ingreso o deseas mas información, selecciona este link para redireccionar:\r\n\r\nhttp://www.umc.edu.ve/admision\r\n\r\nte explicará los pasos necesarios a seguir.\r\n\r\nUna vez realizados todos los pasos puedes ingresar en:\r\n\r\nhttp://www.umc.edu.ve/component/content/article?layout=edit&id=603\r\n\r\npara verificar si ya estas en la lista de los nuevos ingresos.\r\ntoma en cuenta que esta lista se actualiza contantemente, si algo no va bien verifica en la pagina de la UMC la información actualizada', 'ingreso', 'nuevo', 'nuevo ingreso', 'planilla', 'plantilla', 'lista', NULL, NULL, NULL, NULL, 'False', 'nuevo'),
(4, 'El Calendario de inicio del semestre está disponible en el link a continuación:\n\nhttp://www.umc.edu.ve/images/2023calen.jpg\n\nEn él podrás encontrar las fechas de actividades especiales, días de asueto, actos, vacaciones colectivas y curso intensivo. ', 'comienza', 'comienzo', 'inicia', 'inicio', 'empieza', 'comenzar', 'iniciar', 'empezar', 'semestre', 'fecha', 'True', NULL),
(5, 'El Calendario de finalización del semestre está disponible en el link a continuación:\n\nhttp://www.umc.edu.ve/images/2023calen.jpg\n\nEn él podrás encontrar las fechas de actividades especiales, días de asueto, actos, vacaciones colectivas y curso intensivo. ', 'final', 'finaliza', 'termina', 'terminar', 'acaba', 'terminan', 'fin', 'calendario', 'semestre', 'fecha', 'True', NULL),
(6, 'Las fechas de las inscripciones regulares en la UMC serán publicadas en su pagina oficial.\r\n\r\nPara inscribirse en la UMC los pasos a seguir son: \r\n\r\n- Ingresar a la pagina de la marítima:\r\nhttp://www.umc.edu.ve\r\n\r\n- Chequear tu índice académico\r\n\r\n- Anticiparte planificando tu horario antes de las inscripciones.\r\n\r\n- Verificar en el calendario fecha y horario de inscripción según tu índice académico.\r\n\r\n- Cuando te corresponda ingresa en el enlace inscripciones regulares con tu usuario y clave SIRACES.\r\n\r\n- Sigue las instrucciones y descarga tu registro.\r\n\r\nToma en cuenta que algunas cosas pueden cambiar para cada semestre, es recomendable estar atento a la pagina de la UMC y a sus redes, o incluirte en uno de los tantos grupos de WhatsApp', 'materias', 'materia', 'maritima', 'inscribirme', 'inscripcion', 'inscripciones', 'inscribir', 'inscribo', 'planilla', 'plantilla', 'False', 'inscripcion'),
(7, 'Para saber la fecha de las inscripciones de la UMC debe estar atento a su pagina oficial:\r\n\r\nhttp://www.umc.edu.ve\r\n\r\nAhí se estará actualizando esta y más información relevante.\r\nTambién puede verificar si en el Twitter oficial de la UMC se ha publicado algo al respecto\r\n\r\nhttps://twitter.com/u_maritima?lang=es', 'cuando', 'dia', 'fecha', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'True', 'cuando'),
(8, 'Los horarios de la UMC estarán siendo publicados en la pagina oficial de la misma\r\n\r\nhttp://www.umc.edu.ve\r\n\r\nRecuerde observar si el horario es el actualizado', 'horario', 'horarios', 'materias', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'False', 'horario'),
(9, 'holaa :) como puedo ayudarte el día de hoy?', 'hola', 'holaa', 'ola', 'saludos', 'hablame', 'qlq', 'epa', 'hey', 'qloq', 'epale', 'False', 'hola'),
(10, 'buenass :) en que puedo ayudarte?', 'buenas', 'buenass', 'buenos', 'buenas tardes', 'buenas noches', 'dias', NULL, NULL, NULL, NULL, 'False', 'buenas'),
(11, 'deja la groseria y escribe bien', 'culo', 'coño', 'marico', 'mrc', 'puta', 'maldito', 'mierda', 'mamawebo', 'cabron', 'webo', 'False', NULL),
(12, 'excelente! gracias por preguntar :) cuéntame, en que puedo ayudarte el día de hoy?', 'estas', NULL, 'que tal', 'como estas', 'te va', 'tal', 'sientes', 'amaneces', 'te', NULL, 'False', ''),
(13, 'el uniforme habitual para todos los estudiantes de carrera de la UMC o para los veleristas consta de:\r\n- pantalón blue jean clásico.\r\n- franela blanca unicolor con el logo bordado de la UMC.\r\nEl uso de uniformes por parte de los cadetes de la Escuela Náutica de Venezuela tiene como soporte el Reglamento de Uniformes para la Marina Mercante. Mas información disponible en:\r\nhttp://www.umc.edu.ve/universidad/nuestro-uniforme\r\n', 'uniforme', 'vestir', 'ropa', 'vestido', 'vestirse', 'vestirme', 'franela', 'pantalon', 'zapatos', 'es', 'False', 'uniforme'),
(14, 'para los estudiantes en condición de reingreso se debe de llenar una plantilla. siga los pasos que se explican en:\r\nhttp://www.umc.edu.ve/estudios/pregrado/2-uncategorised/452-reingreso?', 'reingreso', 'planilla', 'plantilla', 'reingresar', 'volver', NULL, NULL, NULL, NULL, NULL, 'True', 'reingreso'),
(15, 'si quiere retirar sus documentos de la UMC y/o retirarse totalmente de la universidad, ingrese en el siguiente enlace, lea detalladamente y siga los pasos que se describen:\r\nhttp://www.umc.edu.ve/estudios/pregrado/2-uncategorised/453-retiro-de-documento?', 'retiro', 'documentos', 'salirme', 'retirarme', 'salir', 'documento', 'retirar', 'abandonar', 'dejar', 'salgo', 'True', 'documentos'),
(16, 'para el retiro de una unidad curricular el proceso se llevará a cabo mediante un correo electrónico, que es estrictamente para solicitudes de Retiro de Unidad Curricular, el mismo es: retirosumc@gmail.com, este correo es el único válido para el proceso.\r\nPara mayor información ingrese en:\r\n\r\nhttp://www.umc.edu.ve/estudios/pregrado/2-uncategorised/454-retiro-de-unidad-curricular-y-del-semestre?\r\n', 'unidad', 'curricular', 'retiro', 'materias', 'materia', 'retirar', NULL, NULL, NULL, NULL, 'True', 'materia'),
(17, 'El Proceso de Retiro de Semestre o Congelar el Semestre es de manera presencial, en el horario comprendido de 8:30 am hasta las 12:00 m y de 1:00 pm a 2:00 pm por la taquilla de Registro estudiantil.\r\nPara mayor información ingrese en:\r\n\r\nhttp://www.umc.edu.ve/estudios/pregrado/2-uncategorised/454-retiro-de-unidad-curricular-y-del-semestre?\r\n', 'semestre', 'retirar', 'retiro', 'retirarme', 'congelar', 'congelado', 'congelo', NULL, NULL, NULL, 'True', 'semestre'),
(18, 'La pasantía es un periodo de práctica profesional que los estudiantes deben cumplir para optar a un grado académico. Para ello, se establece un cronograma de actividades y entregas de documentos que deben ser cumplidos por los estudiantes y sus tutores, tanto empresarial como académico. \r\n\r\nEntre las actividades a realizar se encuentran la revisión y evaluación del informe técnico de pasantías, la entrega de documentos exigidos por la coordinación, la revisión y calificación del informe por parte de jurados evaluadores, la carga de las actas de evaluación en correos electrónicos establecidos para cada carrera, y la entrega de la documentación completa en una carpeta o sobre amarillo, según la carrera.\r\n\r\nEs importante cumplir con los lapsos establecidos para poder formar parte del grupo de estudiantes a grado académico en la fecha establecida. Una vez que el informe técnico cumpla con todos los requisitos y correcciones solicitadas, y haya sido aprobado por los tutores y jurados evaluadores, se considerará aprobada la pasantía.\r\n\r\ningrese en el siguiente enlace para tener información mas completa sobre el tema:\r\n\r\nhttp://www.umc.edu.ve/images/Pasantias2023.pdf', 'pasantia', 'pasantias', 'pasante', 'laboral', 'pasantes', 'trabajo', 'que', NULL, NULL, NULL, 'False', 'pasantias'),
(19, 'para ver el pensum de ingeniería marítima entre en los siguientes enlaces:\r\n\r\n* Para mención operaciones:\r\nhttp://www.umc.edu.ve/pdf/escuelas/maritima/pensum/Operaciones.pdf\r\n\r\n* Para mención instalaciones marinas:\r\nhttp://www.umc.edu.ve/pdf/escuelas/maritima/pensum/Instalaciones.pdf \r\n\r\n ', 'pensum', 'maritima', 'marino', 'mercante', 'pensun', 'materias', 'ingenieria', NULL, NULL, NULL, 'False', 'pensum'),
(20, 'para ver el pensum de ingeniería ambiental ingrese en el siguiente enlace:\r\nhttp://www.umc.edu.ve/pdf/escuelas/ingenieria/ambiental/pensum/pensum.pdf', 'pensum', 'pensun', 'materias', 'ambiental', 'ingenieria', NULL, NULL, NULL, NULL, NULL, 'False', 'pensum'),
(21, 'para ver el pensum de lic. Administracion entre en el siguiente enlace:\r\n* Mención Comercio Internacional:\r\nhttp://www.umc.edu.ve/pdf/pensum/PENSUM%20COMERCIO%20INTERNACIONAL%202014.pdf\r\n* Mención Transporte\r\nhttp://www.umc.edu.ve/pdf/pensum/PENSUM%20TRANSPORTE%202014.pdf\r\n', 'pensum', 'pensun', 'materias', 'administracion', NULL, NULL, NULL, NULL, NULL, NULL, 'False', 'pensum'),
(22, 'para ver el pensum de lic. Turismo entre en el siguiente enlace:\r\nhttp://www.umc.edu.ve/pdf/escuelas/sociales/pensum/Plan-de-Estudio-TurismoTercera-modificacion.pdf\r\n', 'pensum', 'pensun', 'materias', 'turismo', NULL, NULL, NULL, NULL, NULL, NULL, 'False', 'pensum'),
(23, 'ingrese en el siguiente enlace para ver el pensum de ingeniería informática:\r\nhttp://www.umc.edu.ve/ingenieria-informatica', 'pensum', 'pensun', 'informatica', 'materias', 'ingenieria', NULL, NULL, NULL, NULL, NULL, 'False', 'pensum'),
(24, 'Todo Estudiante que ingrese a la Universidad Nacional Experimental Marítima del Caribe, lo hará comenzando en el Programa “Velero de Preparación”, en la condición de Estudiante Regular, con total acceso a los beneficios estudiantiles existentes, en cuanto le sea aplicable.\r\nsi estas interesado en el Velero de Preparación selecciona este link para redireccionar:\r\n\r\nhttp://www.umc.edu.ve/estudios/velero-de-preparacion\r\n\r\nahí encontraras toda la información necesaria', 'velero', 'preparacion', 'propedeutico', 'velerista', 'veleristas', NULL, NULL, NULL, NULL, NULL, 'True', 'velero'),
(25, 'Nuestros certificados cursos modelo de la Organización Marítima Internacional (OMI), expedidos por la Universidad Marítima del Caribe (UMC) cubren una amplia gama de temas, como la seguridad en la navegación, la protección del medio ambiente marino, la prevención de la contaminación, la gestión del tráfico marítimo, la seguridad de la carga y la prevención de incendios. Estos cursos son obligatorios para los profesionales que trabajan en la industria marítima.\r\nPara saber cuales son los cursos que ofrece la UMC, como hacerlos o cualquier otra información necesaria visite: \r\nhttp://www.umc.edu.ve/estudios/cursos-stcw', 'omi', 'cursos', 'curso', 'planilla', 'plantilla', NULL, NULL, NULL, NULL, NULL, 'True', 'omi'),
(26, 'En el año 2005 se creó la Fundación Universidad Marítima del Caribe (FUNDAUMC), vinculada a la Universidad Experimental Marítima del Caribe (UMC), con el objetivo de brindar servicios de consultoría, gestión y operaciones en el sector marítimo nacional e internacional. FUNDAUMC cuenta con un grupo de profesionales docentes y ofrece Cursos Avanzados de la Organización Marítima Internacional (OMI) en cumplimiento con las regulaciones internacionales de seguridad marítima. \r\nPara mayor información ingrese en el siguiente link:\r\n\r\nhttp://www.umc.edu.ve/fundaumc', 'fundaumc', 'fundacion', 'inaugurar', 'fundo', NULL, NULL, NULL, NULL, NULL, NULL, 'True', 'fundaumc'),
(27, 'Para acceder a los Estudios Superiores (Postgrado) selecciona este link para redireccionar:\r\n\r\nhttp://www.umc.edu.ve/estudios/estudios-superiores', 'postgrado', 'posgrado', 'superiores', 'postgrados', 'posgrados', 'es', NULL, NULL, NULL, NULL, 'False', 'postgrado'),
(28, 'sea mas especifico, por favor :) 1', 'que', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'True', NULL),
(29, 'La Universidad Nacional Experimental Marítima del Caribe (UMC) ha creado un Programa Nacional de Formación de Técnicos Superiores Universitarios en Transporte Acuático, en colaboración con el Instituto Nacional de Espacios Acuáticos. Este programa tiene como objetivo formar profesionales para la industria marítima en áreas como navegación y operaciones acuáticas. Los estudiantes pueden acceder a la educación universitaria mediante tres modalidades de estudio. El programa busca desarrollar líderes capaces de asumir retos y contribuir al fortalecimiento del sector del transporte acuático.\r\npara mayor información puede acceder a:\r\nhttp://www.umc.edu.ve/estudios/programa-nacional-de-tsu', 'planilla', 'acuatico', 'tsu', 'tecnicos', 'tecnico', 'pnf', NULL, 'plantilla', 'que es', 'es', 'False', 'pnf'),
(30, 'La UMC cuenta con diversos servicios para ofrecer una excelente calidad de estudio, entre esos servicios tenemos los siguientes:\r\n\r\nTransporte Estudiantil\r\nLa Universidad Nacional Experimental Marítima del Caribe, provee a sus estudiantes de un transporte para su traslado seguro tanto en Vargas como hacia y desde Caracas.\r\nPara conocer los horarios disponibles de los transportes selecciona el link a continuación: http://www.umc.edu.ve/servicios#sppb-modal-1485873150\r\n\r\nSalas de Computación\r\nLas Salas de computación son los espacios que garantizan la prestación de servicios tecnológicos a los miembros de la comunidad universitaria, que necesiten acceder a servicios de información y  comunicación en espacios físicos apropiados, para el desarrollo del conocimiento científico propio de las actividades académicas de nuestra institución, con el fin de contribuir en forma significativa en la procura de la calidad de la formación e investigación académica.\r\nPara garantizar la seguridad  física y lógica de los equipos, los usuarios deberán  cumplir con la normativa vigente publicada en cada sala.\r\n\r\nHorario : de lunes a viernes: 8:00 a.m-12:00 p.m / 1:30 p.m–9:00 p.m / sábados: 8:00 a.m - 12:00 p.m\r\n\r\nComedor Estudiantil\r\nLa UMC ofrece servicio de comedor a la población estudiantil en horario: 11:30 am a 1:00 pm.\r\nPara hacer uso del Comedor el estudiante de la UMC debe estar debidamente Uniformado.\r\n\r\nBiblioteca\r\nEsperamos que disfrutes este espacio, y conozcas nuestra biblioteca la cual está dotada de múltiples servicios para atender a nuestros usuarios.\r\nHorario de Atención\r\nDe lunes a viernes de 8:00 am a 8:00 pm y los sábados de 8:00 am a 1:00 pm.\r\n\r\nSi deseas conocer la coordinación de biblioteca y visualizar el catálogo en línea, selecciona a continuación: http://www.umc.edu.ve/coordinacion-de-biblioteca\r\n\r\nServicio Médico\r\n\r\nLa Universidad Marítima del Caribe cuenta con un servicio médico dispuesto a tratar cualquier padecimiento de algún estudiante, profesor, personal administrativo, etc.\r\n\r\nsi desea mas información acerca de los servicios puede visitar:\r\nhttp://www.umc.edu.ve/servicios', 'servicios', 'ofrece', 'servicio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'False', 'servicios'),
(31, 'Transporte Estudiantil\r\n\r\nLa Universidad Nacional Experimental Marítima del Caribe, provee a sus estudiantes de un transporte para su traslado seguro tanto en Vargas como hacia y desde Caracas.\r\nPara conocer los horarios disponibles de los transportes selecciona el link a continuación:\r\n\r\nhttp://www.umc.edu.ve/servicios#sppb-modal-1485873150\r\n\r\nRecuerda tener tu constancia de estudio actualizada para poder disfrutar de este servicio\r\n', 'universidad', 'transporte', 'transportes', 'autobus', NULL, NULL, 'bus', 'ruta', 'rutas', NULL, 'False', 'transporte'),
(32, 'Salas de Computación\r\n\r\nLas Salas de computación son los espacios que garantizan la prestación de servicios tecnológicos a los miembros de la comunidad universitaria, que necesiten acceder a servicios de información y  comunicación en espacios físicos apropiados, para el desarrollo del conocimiento científico propio de las actividades académicas de nuestra institución, con el fin de contribuir en forma significativa en la procura de la calidad de la formación e investigación académica.\r\nPara garantizar la seguridad  física y lógica de los equipos, los usuarios deberán  cumplir con la normativa vigente publicada en cada sala.\r\n\r\nHorario : de lunes a viernes: 8:00 a.m-12:00 p.m / 1:30 p.m–9:00 p.m / sábados: 8:00 a.m - 12:00 p.m\r\n\r\n', 'sala', 'computacion', 'computadora', 'computadoras', 'salas', NULL, NULL, NULL, NULL, NULL, 'False', 'computacion'),
(33, 'Comedor Estudiantil\r\n\r\nLa UMC ofrece servicio de comedor a la población estudiantil en horario: 11:30 am a 1:00 pm.\r\nPara hacer uso del Comedor el estudiante de la UMC debe estar debidamente Uniformado.\r\n\r\nRecuerde también tener su constancia de estudio actualizada \r\n\r\n', 'comedor', 'comida', 'almuerzo', 'almorzar', 'comer', 'estudiantil', NULL, NULL, NULL, 'almorzar', 'False', 'comedor'),
(34, 'Biblioteca\r\nEsperamos que disfrutes este espacio, y conozcas nuestra biblioteca la cual está dotada de múltiples servicios para atender a nuestros usuarios.\r\nHorario de Atención\r\nDe lunes a viernes de 8:00 am a 8:00 pm y los sábados de 8:00 am a 1:00 pm.\r\n\r\nSi deseas conocer la coordinación de biblioteca y visualizar el catálogo en línea, selecciona a continuación: \r\nhttp://www.umc.edu.ve/coordinacion-de-biblioteca\r\n\r\n', 'biblioteca', 'libros', 'libro', 'universidad', 'umc', 'maritima', NULL, NULL, NULL, NULL, 'False', 'biblioteca'),
(35, 'Servicio Médico\r\n\r\nLa Universidad Marítima del Caribe cuenta con un servicio médico dispuesto a tratar cualquier padecimiento de algún estudiante, profesor, personal administrativo, etc.\r\n\r\n', 'medico', 'servicio', 'medicina', 'medicos', 'accidente', 'atencion', 'medica', NULL, NULL, NULL, 'False', 'medico'),
(36, 'en la universidad marítima del caribe dan las siguientes carreras:\r\n\r\n* ingeniería informática\r\n* ingeniería marítima\r\n* ingeniería ambiental\r\n* administración\r\n* turismo\r\n* T.S.U transporte acuático', 'que', 'carreras', 'carrera', 'maritima', NULL, NULL, NULL, NULL, NULL, NULL, 'False', 'carreras'),
(37, 'El Twitter oficial de la UMC es:\r\n\r\nhttps://twitter.com/u_maritima?lang=es\r\n\r\nLa pagina oficial de la UMC es:\r\n\r\nhttp://www.umc.edu.ve\r\n\r\nEn la misma encontraras los correos o los números de contacto que necesites.\r\n\r\n\r\n', 'tw', 'twitter', 'maritima', 'correo', 'numero', 'umc', 'contacto', 'contactos', 'contactar', 'universidad', 'False', 'contacto'),
(38, 'El Twitter oficial de la UMC es:\r\n\r\nhttps://twitter.com/u_maritima?lang=es\r\n\r\nLa pagina oficial de la UMC es:\r\n\r\nhttp://www.umc.edu.ve\r\n\r\nEn la misma encontraras los correos o los números de contacto que necesites.\r\n\r\n\r\n', 'pagina', 'contactos', 'numero', 'maritima', 'umc', 'tuiter', 'numeros', 'correos', 'universidad', 'redes', 'False', 'pagina'),
(39, 'El Twitter oficial de la UMC es:\r\n\r\nhttps://twitter.com/u_maritima?lang=es\r\n\r\nLa pagina oficial de la UMC es:\r\n\r\nhttp://www.umc.edu.ve\r\n\r\nEn la misma encontraras los correos o los números de contacto que necesites.\r\n\r\n\r\n', 'telefono', 'telefonos', NULL, 'maritima', 'umc', NULL, NULL, NULL, 'universidad', NULL, 'False', 'telefono'),
(40, 'el pensum es un documento importante que proporciona una guía detallada sobre lo que los estudiantes deben aprender y cómo deben hacerlo para obtener un título universitario o de posgrado.\r\nsi quiere información sobre el pensum de alguna carrera sea mas especifico', 'que es', 'pensum', 'pensun', 'materias', 'concepto', 'es', NULL, NULL, NULL, NULL, 'False', 'que es'),
(41, 'Ingeniería Informática: Disciplina que combina la ingeniería eléctrica y la ciencia de la computación para diseñar y desarrollar soluciones tecnológicas, tales como sistemas de información, software, redes, y dispositivos móviles, entre otros.\r\npara mas información está el enlace:\r\nhttp://www.umc.edu.ve/ingenieria-informatica', 'que es', 'ingenieria', 'informatica', 'concepto', NULL, 'es', NULL, NULL, NULL, NULL, 'False', 'que es'),
(42, 'Ingeniería Marítima: Disciplina que se enfoca en la planificación, diseño y operación de estructuras y equipos relacionados con la navegación, el transporte marítimo y la exploración del mar, así como también la gestión de recursos naturales y la protección del medio ambiente marino.\r\npara mas información está el enlace: \r\nhttp://www.umc.edu.ve/ingenieria-maritima', 'que es', 'ingenieria', 'maritima', 'marino', 'mercante', 'concepto', 'ingeniero', 'maritimo', 'es', NULL, 'False', 'que es'),
(43, 'Ingeniería Ambiental: Disciplina que aplica los principios de la ingeniería y la ciencia ambiental para mejorar y proteger la calidad del medio ambiente, incluyendo el aire, el agua y el suelo, así como también la salud humana y la biodiversidad.\r\npara mas información está el enlace:\r\nhttp://www.umc.edu.ve/ingenieria-ambiental', 'que es', 'ingenieria', 'ambiental', 'concepto', NULL, 'es', NULL, NULL, NULL, NULL, 'False', 'que es'),
(44, 'Lic. Administración: Disciplina que se enfoca en la gestión de los recursos y procesos de una organización para lograr sus objetivos de manera efectiva y eficiente, a través de la planificación, organización, dirección y control de los recursos humanos, financieros y materiales.\r\nPara mas información está el enlace.\r\nhttp://www.umc.edu.ve/licenciatura-administracion', 'que es', 'concepto', 'administracion', NULL, 'es', NULL, NULL, NULL, NULL, NULL, 'False', 'que es'),
(45, 'Lic. Turismo: Disciplina que abarca el estudio y la gestión de la industria turística, que incluye la planificación turística, la gestión hotelera, la organización de eventos y la promoción turística, así como también el desarrollo sostenible del turismo y la protección del patrimonio cultural y natural.\r\nPara mas información está el enlace:\r\nhttp://www.umc.edu.ve/licenciatura-turismo', 'que es', 'concepto', 'turismo', NULL, 'es', NULL, NULL, NULL, NULL, NULL, 'False', 'que es'),
(46, 'Pueden verse un máximo de 15 semestres, si en ese tiempo el estudiante no completa las unidades de créditos requeridas, se inválida su avance por la carrera y la pierde por factor 15. No obstante, pueden solicitarse 3 semestres adicionales, si se demuestra que puede completarse las unidades de créditos faltantes en ese periodo de tiempo', 'cuantos', 'semestres', 'factor', 'cuanto', 'maximo', NULL, NULL, NULL, NULL, NULL, 'False', ''),
(47, 'Para resonder su duda le invito a leer el reglamento General de la UMC \r\n\r\nhttp://www.umc.edu.ve/pdf/reglamentos/Reglamento%20General%20UMC.pdf', 'reglamento', 'regla', 'reglas', 'normas', 'norma', NULL, NULL, NULL, NULL, NULL, 'True', 'reglamento'),
(48, 'Las materias electivas son materias complementarias de la carrera, que son de carácter opcional, pudiendo el estudiante seleccionar cuáles y cuántas cursar. El mínimo de electivas dependerá de cada carrera, ya que lo único que se requiere es que completo los créditos faltantes para el total de la carrera', 'electiva', 'electivas', NULL, NULL, 'que', NULL, NULL, NULL, NULL, NULL, 'False', ''),
(49, 'sea mas especifico por favor :) 3', 'ingenieria', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'True', NULL),
(50, 'Siga en el enlace para la pagina de la UMC:\n\nhttp://www.umc.edu.ve', 'universidad', 'umc', 'maritima', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'False', NULL),
(51, 'Un pregrado se refiere a un programa académico de nivel universitario que se realiza después de la educación secundaria y antes de la obtención de un título de posgrado. También se le conoce como carrera de grado o licenciatura.\r\npara mas información puede ingresar en:\r\nhttp://www.umc.edu.ve/estudios/pregrado', 'pregrado', 'que', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'True', 'pregrado'),
(52, 'el titulo de Ingeniero Ambiental egresado de la UMC no cuenta con menciones. \r\npara mas información puede consultar:\r\nhttp://www.umc.edu.ve/ingenieria-ambiental\r\n', 'mencion', 'menciones', 'ambiental', 'rama', 'ramas', 'ingenieria', NULL, NULL, NULL, NULL, 'False', 'mencion'),
(53, 'las menciones de ingeniería marítima son:\r\n* Mención instalaciones Marinas\r\n* Mención operaciones\r\npara mas información puede consultar:\r\nhttp://www.umc.edu.ve/ingenieria-maritima\r\n', 'mencion', 'menciones', 'maritima', 'rama', 'ramas', 'ingenieria', NULL, NULL, NULL, NULL, 'False', 'mencion'),
(54, 'las menciones de ingeniería informática son:\r\n* Mención Gestión de Datos\r\n* Mención Seguridad informática \r\n* Mención automatización de procesos\r\n* Mención Redes y telecomunicaciones\r\npara mas información puede consultar:\r\nhttp://www.umc.edu.ve/ingenieria-informatica\r\n', 'mencion', 'menciones', 'informatica', 'rama', 'ramas', 'ingenieria', NULL, NULL, NULL, NULL, 'False', 'mencion'),
(55, 'las menciones que otorga Lic. Administracion son:\r\n* Mención Comercio internacional\r\n* Mención Transporte\r\npara mas información puede consultar:\r\nhttp://www.umc.edu.ve/licenciatura-administracion\r\n', 'mencion', 'menciones', 'administracion', 'rama', 'ramas', NULL, NULL, NULL, NULL, NULL, 'False', 'mencion'),
(56, 'Titulo que otorga\r\n* Técnico Superior Universitario en Turismo.\r\n* Licenciado en Turismo.\r\npara mas información puede consultar:\r\nhttp://www.umc.edu.ve/licenciatura-turismo\r\n', 'mencion', 'menciones', 'turismo', 'rama', 'ramas', NULL, NULL, NULL, NULL, NULL, 'False', 'mencion'),
(57, 'La Universidad Nacional Experimental Marítima del Caribe (UMC) ha creado un Programa Nacional de Formación de Técnicos Superiores Universitarios en Transporte Acuático, en colaboración con el Instituto Nacional de Espacios Acuáticos. Este programa tiene como objetivo formar profesionales para la industria marítima en áreas como navegación y operaciones acuáticas. Los estudiantes pueden acceder a la educación universitaria mediante tres modalidades de estudio. El programa busca desarrollar líderes capaces de asumir retos y contribuir al fortalecimiento del sector del transporte acuático.\r\npara mayor información puede acceder a:\r\nhttp://www.umc.edu.ve/estudios/programa-nacional-de-tsu', 'planilla', 'acuatico', 'tsu', 'tecnicos', 'tecnico', 'pnf', 'transporte', 'plantilla', 'que es', NULL, 'False', 'tsu'),
(58, 'A través del módulo Siraces, puedes ver registro estudiantil y constancia de estudios', 'mis', 'notas', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'True', NULL),
(59, 'actualmente la carnetización en la UMC no esta disponible, de todas maneras aquí dejo un link que lo va a redireccionar con toda la información:\r\n\r\nhttp://www.umc.edu.ve/carnetizacion ', 'carnet', 'carnetizacion', 'carne', 'vencido', NULL, NULL, NULL, NULL, NULL, NULL, 'True', 'carnet'),
(60, 'Las dependencias de la UMC consta de:\r\n\r\n1)Rectorado\r\nC/A Guillermo Antonio Riut Hernández (Rector).\r\n\r\nEl rectorado se constituye por:\r\n-Rectorado\r\n-Coordinación de Consultoria Jurídica\r\n-Coordinación de Gestión de la Calidad\r\n-C.G de Asuntos Rectorales\r\n\r\n2)Vicerrectorado Académico\r\nC/A Edgar Andrés Rodríguez Alemán (Vicerrector Académico).\r\n\r\nEl vicerrectorado académico se constituye por:\r\n-Vicerrectorado Académico\r\n-Dirección General Académica\r\n-Escuela de Náutica de Venezuela\r\n-Escuela de Ingeniería\r\n-Escuela de Ciencias Sociales\r\n-Escuela de Estudios Superiores\r\n-Coordinación de Currículo\r\n-Coordinación de Biblioteca\r\n-Desarrollo Estudiantil\r\n-Dirección de Interacción con las Comunidades\r\n\r\n3)Vicerrectorado Administrativo\r\nC/A Gustavo Bustamante (Vicerrector Administrativo).\r\n\r\nEl vicerrectorado administrativo se constituye por:\r\n-Vicerrectorado Administrativo\r\n-C.G Recursos Humanos\r\n-C.G. Administración\r\n-C.G Planta Física y Equipamiento\r\n-C.G Planificación y Presupuesto\r\n\r\n4)Secretaría General\r\nJ/M Jesús Suárez (Secretario General)\r\n\r\nLa secretaría general se constituye por:\r\n-Secretaria General\r\n-Coordinación de Asuntos Secretariales\r\n-Coordinación de Archivo General y Control Estadístico\r\n-Coordinación de Registro Estudiantil\r\n-Coordinación de Tecnología de Información y Comunicación\r\n\r\n\r\n', 'dependencias', 'consta', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'True', 'dependencias'),
(61, 'Insolvencia es la falta de algún documento necesario para estudiar en la UMC, debe de ir directamente a la universidad donde se le aclarará cual es el documento faltante', 'insolvencia', 'insolvente', 'que', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'False', NULL),
(62, 'si está interesad@ en conocer los símbolos de nuestra querida universidad ingrese en:\r\n\r\nhttp://www.umc.edu.ve/universidad/nuestros-simbolos\r\n\r\no si tiene interés en saber cual es la misión, visión y los valores en la UMC puede ingresar en:\r\n\r\nhttp://www.umc.edu.ve/universidad/valores  \r\n\r\ndonde tendrá mayor información ', 'himno', 'simbolo', 'simbolos', 'escudo', 'mision', 'vision', 'valores', NULL, NULL, NULL, 'True', NULL),
(63, 'para solicitud de trabajo de especial o copias que excedan los limites debe llenar el siguiente formulario:\r\n\r\nhttp://www.umc.edu.ve/pdf/ata/UDI-002%20SOLICITUDTRABAJOESPECIALES.pdf\r\n\r\neste formulario permite a las diferentes dependencias de la universidad solicitar reproducciones especiales o copias adicionales de documentos institucionales que son necesarios para las actividades académicas y administrativas.', 'especiales', 'especial', 'trabajo', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'False', 'especial'),
(64, 'Para verificar que el aspirante cumpla con las condiciones médicas requeridas para ingresar a las carreras de\r\nIngeniería Marítima y TSU Transporte Acuático, según los lineamientos del STCW (Manila-2010). Debe realizar una ficha medica de completando la siguiente planilla:\r\n\r\nhttp://www.umc.edu.ve/pdf/ata/documentos/Ficha-Medica-Est.pdf\r\n\r\n', 'ficha', 'planilla', 'medica', 'tsu', 'maritima', NULL, NULL, NULL, NULL, NULL, 'False', 'medica'),
(65, 'La Coordinación de REGISTRO ESTUDIANTIL\r\n\r\ntiene como finalidad mantener el registro académico del estudiantado desde que ingresan a esta Casa de Estudios hasta su egreso, el cual se encuentra englobado en tres procesos: Ingreso, Control de Estudios, Permanencia y Egreso.\r\n\r\nofrece Servicios como:\r\n\r\nPreinscripciones por Internet.\r\nInscripciones por Internet para Alumnos Regulares.\r\nSolicitud de Constancias de Estudios por Internet\r\nRetiro de Unidad Curricular o del Semestre.\r\nMódulo de Estudiantes (Consulta de Notas - Intranet).\r\nEnvío y recepción de información académica a la comunidad estudiantil  a través de un Correo Institucional ().\r\nDescarga de Constancia de Calificación y Registro de Inscripción por Internet.\r\nRecepción de Documentos Académicos para su validación (firma y sello).  \r\n\r\npara acceder a toda esta y mas información puede ingresar en:\r\n\r\nhttp://www.umc.edu.ve/component/content/article?layout=edit&id=47\r\n\r\nNota: La recepción de los documentos será de Lunes a Jueves; de 8:30am a 12:00pm y de 1:00pm a 2:00pm', 'registro', 'estudiantil', 'coordinacion', 'documentos', 'horario', 'horarios', NULL, NULL, NULL, NULL, 'False', NULL),
(66, 'El periodo intensivo tiene como propósito incentivar la formación continua del estudiante en lapsos de vacaciones de estudiantes y profesores, mediante la oferta de materias requeridas para proseguir su plan de estudio.\r\n\r\nSi deseas conocer más sobre el intensivo, deberás estar atento a la información que se suba en la página de la UMC.\r\n\r\nhttp://www.umc.edu.ve/', 'intensivo', 'verano', 'intensivos', 'que', NULL, NULL, NULL, NULL, NULL, NULL, 'False', ''),
(67, 'Pasos para la obtención de Solvencia en CAGCE:\n\nSolicitud de Solvencias para Reingreso, Cambio de Carrera, Cambio de Mención, Equivalencias y Exámen de Suficiencia.\n\nRequisitos:\n\n· Cédula laminada.\n· Estudiantes de Ingeniería Marítima deben traer ficha médica actualizada y firmada por los médicos autorizados por el Instituto Nacional de Espacios Acuáticos (INEA).', 'solvencia', 'insolvencia', 'solvente', 'insolvente', NULL, NULL, NULL, NULL, NULL, NULL, 'True', ''),
(68, 'Pasos para el Retiro de Documentos:\r\n\r\nRequisitos:\r\n· Descargar la planilla que se encuentra en la página de la UMC: http://www.umc.edu.ve/licenciatura-administracion/2-uncategorised/453-retiro-de-documento?ml=1\r\n\r\n· Llenar un (1) original y tres (3) copias del formato de solicitud antes mencionado.\r\n\r\n· Entregar los cuatro (4) ejemplares en la taquilla de la Unidad de Archivo Ubicada en la Planta Baja del Edificio Administrativo. (se reciben los días Lunes y Martes, y se retiran los días Jueves a partir de la 1:00 p.m).', 'retiro', 'documentos', 'retirar', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'False', 'retiro'),
(69, 'Para obtener tu registro de inscripción debes solicitarla por la taquilla del Edif. Administrativo ó entrar a tu Zona de estudiantes (SIRACES) al final de la página en el siguiente link: http://www.umc.edu.ve/', 'registro', 'inscripcion', 'mi', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'False', 'registro'),
(70, 'Para acceder a SIRACES debes entrar a la página de la UMC http://www.umc.edu.ve/, al final de la página se encuentra el portal a Zona de estudiantes. Recuerda que debes leer el instructivo que se refleja en dicho portal y si no posees tu validación deberás ir personalmente a la taquilla del edificio administrativo.\r\n\r\nPara asuntos referentes al Sistema SIRACES enviar su petición al siguiente correo:\r\n\r\nsiraces.umc.ve@gmail.com', 'siraces', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'True', ''),
(71, 'Si deseas presentar el exámen de suficiencia debes ingresar al siguiente link: http://www.umc.edu.ve/component/content/article?id=575:examen-de-suficiencia-2022\n\nEn la página podrás detallar los requisitos, la planilla que debes descargar y donde debes entregarla.\n\nRecuerda que dicha planilla tiene un tope de recepción que se estará actualizando de acuerdo al calendario académico.', 'suficiencia', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'True', 'suficiencia'),
(72, 'Si deseas solicitar cambio de carrera o mención debes ingresar al siguiente link: http://www.umc.edu.ve/component/content/article?id=517:solicitud-cambio-de-carrera\r\n\r\nEn la página podrás detallar los requisitos, la planilla que debes descargar junto al instructivo y donde debes entregarla.\r\n\r\nRecuerda que dicha planilla tiene un tope de recepción que se estará actualizando de acuerdo al calendario académico.', 'cambio', 'carrera', 'mencion', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'False', 'cambio'),
(73, 'Para solicitar Equivalencias Externas o Internas\ndebes acceder aquí: \n\nExternas: http://www.umc.edu.ve/component/content/article?layout=edit&id=298\n\nInternas: http://www.umc.edu.ve/registro-estudiantil/42-dependencias/secretaria/registro-estudiantil/197-cambio-de-carrera\n\nEn la página podrás detallar los requisitos y la planilla que debes descargar junto al instructivo. La debes entregar en taquilla del Edif. Administrativo.\n\nRecuerda que dicha planilla tiene un tope de recepción que se estará actualizando de acuerdo al calendario académico.', 'equivalencia', 'equivalencias', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'True', 'equivalencia'),
(74, 'Tipos de clave para ingreso:\r\n\r\n-Clave de Campo\r\nEs la clave de inscripción.\r\n\r\n-Clave de SIRACES\r\nEs la clave de zona de estudiantes.\r\n\r\nSi presentas algún problema con respecto a tu clave o usuario de SIRACES o Zona de Estudiante, dirígete a la taquilla del edificio administrativo para mayor información y ayuda.', 'clave', 'usuario', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'True', 'clave'),
(75, 'Probatorio es un periodo de prueba posterior a un semestre donde el estudiante obtuvo un promedio inferior al mínimo aprobatorio (12), dónde tendrán la última prioridad de inscripción y deberán alcanzar un promedio de 12 o superior durante dicho periodo para seguir su estadía en la universidad (Revisa en el reglamento, no estoy muy segura de si deja inscribir la misma cantidad de unidades de créditos o la reduce.', 'probatorio', NULL, NULL, NULL, 'que', NULL, NULL, NULL, NULL, NULL, 'False', 'probatorio'),
(76, 'Prelar es la antelación o la previa de n cantidad de materias que deben ser cursadas y aprobadas con respecto a otra. De ese modo, si una de esas n materias no está aprobada, no puede inscribirse la materia en cuestión', 'prelar', 'prela', 'prelo', 'que', 'prelado', NULL, NULL, NULL, NULL, NULL, 'False', 'prelar'),
(77, 'El servicio social es un requisito obligatorio para cualquier institución, su finalidad es formar profesionales integrales con consciencia social. En la UMC, se establece que deben (a) Aprobarse todas las materias de primer a cuarto semestre del pensum, para cualquier carrera, o (b) contar con el 50% de unidades de créditos aprobadas del total de la carrera', 'servicio', 'social', 'que', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'False', NULL),
(78, 'Las unidades de créditos son usados para expresar en una magnitud el valor de una materia. Para completar una determinada carrera, deben reunirse una cantidad específica de unidades de créditos', 'unidades', 'creditos', 'unidad', 'credito', 'que', NULL, NULL, NULL, NULL, NULL, 'False', NULL),
(79, 'En el reglamento, se expresa que el máximo de unidades de créditos es 24 UC para cada inscripción. Se puede pedir extra créditos, agregando 4 créditos adicionales para un total de 28 UC ( a. Revisa el reglamento, no estoy segura si se menciona un mínimo y b. Los extra créditos se piden igual que una solicitud extemporánea, esa la misma planilla pero llenas la parte que dice extra créditos )', 'extracredito', 'extra', 'credito', NULL, 'que', NULL, NULL, NULL, NULL, NULL, 'False', NULL),
(80, 'La Universidad Nacional Experimental Marítima del Caribe (UMC) tiene su sede principal en la Avenida el Ejército de Catia la Mar, estado La Guaira.', 'ubicada', 'sede', 'encuentra', 'universidad', 'umc', 'maritima', 'queda', 'esta', NULL, NULL, 'False', 'sede'),
(81, 'La ubicación de las aulas, canchas, comedor, servicio médico, edificio administrativo y talleres se encuentran en el link de abajo, puedes seleccionar y ubicar lo que estás buscando específicamente.\n\n https://drive.google.com/file/d/1ODEyaBfEuYq5mRltqYV0kISUHYenuE-x/view?usp=drive_link', 'baño', 'aula', 'salon', 'salones', 'laboratorio', 'cancha', 'talleres', 'donde', 'queda', 'cual', 'False', NULL);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `respuestas`
--
ALTER TABLE `respuestas`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `respuestas`
--
ALTER TABLE `respuestas`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=82;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
